[OK]#[OK]![OK]/[OK]u[OK]s[OK]r[OK]/[OK]b[OK]i[OK]n[OK]/[OK]e[OK]n[OK]v[OK] [OK]p[OK]w[OK]s[OK]h[OK][OK]
[OK]#[OK] [OK]C[OK]r[OK]o[OK]s[OK]s[OK]-[OK]p[OK]l[OK]a[OK]t[OK]f[OK]o[OK]r[OK]m[OK] [OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]s[OK]y[OK]n[OK]c[OK] [OK]v[OK]e[OK]r[OK]i[OK]f[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK][OK]
[OK]#[OK] [OK]V[OK]e[OK]r[OK]i[OK]f[OK]i[OK]e[OK]s[OK] [OK]a[OK]l[OK]l[OK] [OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]r[OK]e[OK]f[OK]e[OK]r[OK]e[OK]n[OK]c[OK]e[OK]s[OK] [OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]t[OK]h[OK]e[OK] [OK]a[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK] [OK]V[OK]E[OK]R[OK]S[OK]I[OK]O[OK]N[OK] [OK]f[OK]i[OK]l[OK]e[OK][OK]
[OK][OK]
[OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]A[OK]c[OK]t[OK]i[OK]o[OK]n[OK]P[OK]r[OK]e[OK]f[OK]e[OK]r[OK]e[OK]n[OK]c[OK]e[OK] [OK]=[OK] [OK]"[OK]S[OK]t[OK]o[OK]p[OK]"[OK][OK]
[OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]=[OK] [OK]S[OK]p[OK]l[OK]i[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]-[OK]P[OK]a[OK]r[OK]e[OK]n[OK]t[OK] [OK]$[OK]P[OK]S[OK]S[OK]c[OK]r[OK]i[OK]p[OK]t[OK]R[OK]o[OK]o[OK]t[OK][OK]
[OK][OK]
[OK]$[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]F[OK]i[OK]l[OK]e[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]s[OK]r[OK]c[OK]/[OK]i[OK]n[OK]t[OK]e[OK]r[OK]f[OK]a[OK]c[OK]e[OK]s[OK]/[OK]t[OK]u[OK]i[OK]/[OK]V[OK]E[OK]R[OK]S[OK]I[OK]O[OK]N[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]-[OK]n[OK]o[OK]t[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]F[OK]i[OK]l[OK]e[OK])[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]E[OK]R[OK]R[OK]O[OK]R[OK]:[OK] [OK]V[OK]E[OK]R[OK]S[OK]I[OK]O[OK]N[OK] [OK]f[OK]i[OK]l[OK]e[OK] [OK]n[OK]o[OK]t[OK] [OK]f[OK]o[OK]u[OK]n[OK]d[OK] [OK]a[OK]t[OK] [OK]$[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]F[OK]i[OK]l[OK]e[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]R[OK]e[OK]d[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]x[OK]i[OK]t[OK] [OK]1[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK] [OK]=[OK] [OK]([OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]F[OK]i[OK]l[OK]e[OK] [OK]-[OK]R[OK]a[OK]w[OK])[OK].[OK]T[OK]r[OK]i[OK]m[OK]([OK])[OK][OK]
[OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK] [OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]:[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]C[OK]y[OK]a[OK]n[OK][OK]
[OK][OK]
[OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]=[OK] [OK]@[OK]([OK])[OK][OK]
[OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK] [OK]=[OK] [OK]0[OK][OK]
[OK][OK]
[OK]#[OK] [OK]1[OK].[OK] [OK]C[OK]a[OK]r[OK]g[OK]o[OK].[OK]t[OK]o[OK]m[OK]l[OK][OK]
[OK]$[OK]C[OK]a[OK]r[OK]g[OK]o[OK]T[OK]o[OK]m[OK]l[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]s[OK]r[OK]c[OK]/[OK]i[OK]n[OK]t[OK]e[OK]r[OK]f[OK]a[OK]c[OK]e[OK]s[OK]/[OK]t[OK]u[OK]i[OK]/[OK]C[OK]a[OK]r[OK]g[OK]o[OK].[OK]t[OK]o[OK]m[OK]l[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]C[OK]a[OK]r[OK]g[OK]o[OK]T[OK]o[OK]m[OK]l[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]C[OK]a[OK]r[OK]g[OK]o[OK]T[OK]o[OK]m[OK]l[OK] [OK]-[OK]R[OK]a[OK]w[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]-[OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]'[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]\[OK]s[OK]*[OK]=[OK]\[OK]s[OK]*[OK]"[OK]([OK][[OK]^[OK]"[OK]][OK]+[OK])[OK]"[OK]'[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]c[OK]a[OK]r[OK]g[OK]o[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]=[OK] [OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]a[OK]r[OK]g[OK]o[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]C[OK]a[OK]r[OK]g[OK]o[OK].[OK]t[OK]o[OK]m[OK]l[OK]:[OK] [OK]$[OK]c[OK]a[OK]r[OK]g[OK]o[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]C[OK]a[OK]r[OK]g[OK]o[OK].[OK]t[OK]o[OK]m[OK]l[OK]:[OK] [OK]$[OK]c[OK]a[OK]r[OK]g[OK]o[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]2[OK].[OK] [OK]n[OK]p[OK]m[OK] [OK]s[OK]h[OK]i[OK]m[OK] [OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK].[OK]j[OK]s[OK]o[OK]n[OK][OK]
[OK]$[OK]N[OK]p[OK]m[OK]P[OK]k[OK]g[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK]s[OK]/[OK]n[OK]p[OK]m[OK]-[OK]s[OK]h[OK]i[OK]m[OK]/[OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK].[OK]j[OK]s[OK]o[OK]n[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]N[OK]p[OK]m[OK]P[OK]k[OK]g[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]n[OK]p[OK]m[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]N[OK]p[OK]m[OK]P[OK]k[OK]g[OK] [OK]|[OK] [OK]C[OK]o[OK]n[OK]v[OK]e[OK]r[OK]t[OK]F[OK]r[OK]o[OK]m[OK]-[OK]J[OK]s[OK]o[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]n[OK]p[OK]m[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]n[OK]p[OK]m[OK] [OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK].[OK]j[OK]s[OK]o[OK]n[OK]:[OK] [OK]$[OK]([OK]$[OK]n[OK]p[OK]m[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]n[OK]p[OK]m[OK] [OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK].[OK]j[OK]s[OK]o[OK]n[OK]:[OK] [OK]$[OK]([OK]$[OK]n[OK]p[OK]m[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]3[OK].[OK] [OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]s[OK]h[OK][OK]
[OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]S[OK]h[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]s[OK]h[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]S[OK]h[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]S[OK]h[OK] [OK]-[OK]R[OK]a[OK]w[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]-[OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]'[OK]R[OK]E[OK]L[OK]E[OK]A[OK]S[OK]E[OK]_[OK]T[OK]A[OK]G[OK]=[OK]"[OK]v[OK]([OK][[OK]^[OK]"[OK]][OK]+[OK])[OK]"[OK]'[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]s[OK]h[OK] [OK]R[OK]E[OK]L[OK]E[OK]A[OK]S[OK]E[OK]_[OK]T[OK]A[OK]G[OK]:[OK] [OK]v[OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]v[OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]s[OK]h[OK]:[OK] [OK]v[OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]4[OK].[OK] [OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]p[OK]s[OK]1[OK][OK]
[OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]P[OK]s[OK]1[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]p[OK]s[OK]1[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]P[OK]s[OK]1[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]I[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK]P[OK]s[OK]1[OK] [OK]-[OK]R[OK]a[OK]w[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]-[OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]'[OK]\[OK]$[OK]R[OK]e[OK]l[OK]e[OK]a[OK]s[OK]e[OK]T[OK]a[OK]g[OK]\[OK]s[OK]*[OK]=[OK]\[OK]s[OK]*[OK]"[OK]v[OK]([OK][[OK]^[OK]"[OK]][OK]+[OK])[OK]"[OK]'[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]p[OK]s[OK]1[OK] [OK]R[OK]e[OK]l[OK]e[OK]a[OK]s[OK]e[OK]T[OK]a[OK]g[OK]:[OK] [OK]v[OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]v[OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]i[OK]n[OK]s[OK]t[OK]a[OK]l[OK]l[OK].[OK]p[OK]s[OK]1[OK]:[OK] [OK]v[OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]5[OK].[OK] [OK]H[OK]o[OK]m[OK]e[OK]b[OK]r[OK]e[OK]w[OK] [OK]f[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK] [OK]t[OK]e[OK]m[OK]p[OK]l[OK]a[OK]t[OK]e[OK][OK]
[OK]$[OK]B[OK]r[OK]e[OK]w[OK]F[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]i[OK]n[OK]g[OK]/[OK]h[OK]o[OK]m[OK]e[OK]b[OK]r[OK]e[OK]w[OK]/[OK]o[OK]d[OK]d[OK]-[OK]d[OK]a[OK]s[OK]h[OK]b[OK]o[OK]a[OK]r[OK]d[OK].[OK]r[OK]b[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]B[OK]r[OK]e[OK]w[OK]F[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]B[OK]r[OK]e[OK]w[OK]F[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK] [OK]-[OK]R[OK]a[OK]w[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]-[OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]'[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]"[OK]([OK][[OK]^[OK]"[OK]][OK]+[OK])[OK]"[OK]'[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]H[OK]o[OK]m[OK]e[OK]b[OK]r[OK]e[OK]w[OK] [OK]f[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK]:[OK] [OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]H[OK]o[OK]m[OK]e[OK]b[OK]r[OK]e[OK]w[OK] [OK]f[OK]o[OK]r[OK]m[OK]u[OK]l[OK]a[OK]:[OK] [OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]6[OK].[OK] [OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]t[OK]e[OK]m[OK]p[OK]l[OK]a[OK]t[OK]e[OK][OK]
[OK]$[OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]i[OK]n[OK]g[OK]/[OK]w[OK]i[OK]n[OK]g[OK]e[OK]t[OK]/[OK]O[OK]d[OK]d[OK]E[OK]s[OK]s[OK]e[OK]n[OK]t[OK]i[OK]a[OK]l[OK]s[OK].[OK]O[OK]d[OK]d[OK]D[OK]a[OK]s[OK]h[OK]b[OK]o[OK]a[OK]r[OK]d[OK].[OK]y[OK]a[OK]m[OK]l[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]-[OK]R[OK]a[OK]w[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]c[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]-[OK]m[OK]a[OK]t[OK]c[OK]h[OK] [OK]'[OK]P[OK]a[OK]c[OK]k[OK]a[OK]g[OK]e[OK]V[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK]:[OK]\[OK]s[OK]*[OK]([OK]\[OK]S[OK]+[OK])[OK]'[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK]:[OK] [OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]W[OK]i[OK]n[OK]g[OK]e[OK]t[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK]:[OK] [OK]$[OK]([OK]$[OK]M[OK]a[OK]t[OK]c[OK]h[OK]e[OK]s[OK][[OK]1[OK]][OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]7[OK].[OK] [OK]S[OK]c[OK]o[OK]o[OK]p[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]t[OK]e[OK]m[OK]p[OK]l[OK]a[OK]t[OK]e[OK][OK]
[OK]$[OK]S[OK]c[OK]o[OK]o[OK]p[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]J[OK]o[OK]i[OK]n[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]R[OK]o[OK]o[OK]t[OK] [OK]"[OK]p[OK]a[OK]c[OK]k[OK]a[OK]g[OK]i[OK]n[OK]g[OK]/[OK]s[OK]c[OK]o[OK]o[OK]p[OK]/[OK]o[OK]d[OK]d[OK]-[OK]d[OK]a[OK]s[OK]h[OK]b[OK]o[OK]a[OK]r[OK]d[OK].[OK]j[OK]s[OK]o[OK]n[OK]"[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]T[OK]e[OK]s[OK]t[OK]-[OK]P[OK]a[OK]t[OK]h[OK] [OK]$[OK]S[OK]c[OK]o[OK]o[OK]p[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK]+[OK]+[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]s[OK]c[OK]o[OK]o[OK]p[OK] [OK]=[OK] [OK]G[OK]e[OK]t[OK]-[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK] [OK]$[OK]S[OK]c[OK]o[OK]o[OK]p[OK]M[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK] [OK]|[OK] [OK]C[OK]o[OK]n[OK]v[OK]e[OK]r[OK]t[OK]F[OK]r[OK]o[OK]m[OK]-[OK]J[OK]s[OK]o[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]([OK]$[OK]s[OK]c[OK]o[OK]o[OK]p[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]-[OK]n[OK]e[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]+[OK]=[OK] [OK]"[OK]S[OK]c[OK]o[OK]o[OK]p[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK]:[OK] [OK]$[OK]([OK]$[OK]s[OK]c[OK]o[OK]o[OK]p[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK])[OK] [OK]([OK]e[OK]x[OK]p[OK]e[OK]c[OK]t[OK]e[OK]d[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK])[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]â[OK]œ[OK]“[OK] [OK]S[OK]c[OK]o[OK]o[OK]p[OK] [OK]m[OK]a[OK]n[OK]i[OK]f[OK]e[OK]s[OK]t[OK]:[OK] [OK]$[OK]([OK]$[OK]s[OK]c[OK]o[OK]o[OK]p[OK].[OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK])[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]#[OK] [OK]S[OK]u[OK]m[OK]m[OK]a[OK]r[OK]y[OK][OK]
[OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]"[OK][OK]
[OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK] [OK]$[OK]C[OK]h[OK]e[OK]c[OK]k[OK]e[OK]d[OK] [OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]s[OK]o[OK]u[OK]r[OK]c[OK]e[OK]s[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]C[OK]y[OK]a[OK]n[OK][OK]
[OK][OK]
[OK]i[OK]f[OK] [OK]([OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK].[OK]C[OK]o[OK]u[OK]n[OK]t[OK] [OK]-[OK]g[OK]t[OK] [OK]0[OK])[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]V[OK]E[OK]R[OK]S[OK]I[OK]O[OK]N[OK] [OK]M[OK]I[OK]S[OK]M[OK]A[OK]T[OK]C[OK]H[OK]:[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]R[OK]e[OK]d[OK][OK]
[OK] [OK] [OK] [OK] [OK]$[OK]E[OK]r[OK]r[OK]o[OK]r[OK]s[OK] [OK]|[OK] [OK]F[OK]o[OK]r[OK]E[OK]a[OK]c[OK]h[OK]-[OK]O[OK]b[OK]j[OK]e[OK]c[OK]t[OK] [OK]{[OK] [OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK] [OK] [OK]-[OK] [OK]$[OK]_[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]Y[OK]e[OK]l[OK]l[OK]o[OK]w[OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]x[OK]i[OK]t[OK] [OK]1[OK][OK]
[OK]}[OK][OK]
[OK][OK]
[OK]W[OK]r[OK]i[OK]t[OK]e[OK]-[OK]H[OK]o[OK]s[OK]t[OK] [OK]"[OK]â[OK]œ[OK]“[OK] [OK]A[OK]l[OK]l[OK] [OK]v[OK]e[OK]r[OK]s[OK]i[OK]o[OK]n[OK] [OK]s[OK]o[OK]u[OK]r[OK]c[OK]e[OK]s[OK] [OK]m[OK]a[OK]t[OK]c[OK]h[OK]:[OK] [OK]$[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]t[OK]a[OK]t[OK]i[OK]v[OK]e[OK]"[OK] [OK]-[OK]F[OK]o[OK]r[OK]e[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]C[OK]o[OK]l[OK]o[OK]r[OK] [OK]G[OK]r[OK]e[OK]e[OK]n[OK][OK]
[OK]e[OK]x[OK]i[OK]t[OK] [OK]0[OK][OK]
[OK]
